const phrases = [
{ en: "That makes sense.", jp: "なるほどね" },
{ en: "I see.", jp: "なるほど" },
{ en: "I get it.", jp: "分かった" },
{ en: "I don’t get it.", jp: "分からない" },
{ en: "No way!", jp: "まさか" },
{ en: "Seriously?", jp: "マジで" },
{ en: "That’s crazy.", jp: "やばいね" },
{ en: "That’s awesome.", jp: "最高" },
{ en: "That’s cool.", jp: "いいね" },
{ en: "I didn’t know that.", jp: "知らなかった" },
{ en: "Interesting.", jp: "面白いね" },
{ en: "Fair enough.", jp: "まあ納得" },
{ en: "I guess so.", jp: "たぶんそう" },
{ en: "That’s true.", jp: "それはそう" },
{ en: "Makes sense.", jp: "理にかなってる" },
{ en: "I agree.", jp: "同意" },
{ en: "I totally agree.", jp: "完全に同意" },
{ en: "Sounds good.", jp: "いいね" },
{ en: "That works.", jp: "それでOK" },
{ en: "I’m down.", jp: "やる" },
{ en: "Let’s do it.", jp: "やろう" },
{ en: "Why not?", jp: "いいじゃん" },
{ en: "I’m in.", jp: "参加する" },
{ en: "I’m good with that.", jp: "それでいいよ" },
{ en: "That’s fine.", jp: "問題ない" },
{ en: "I don’t mind.", jp: "気にしない" },
{ en: "Up to you.", jp: "任せる" },
{ en: "Either works.", jp: "どっちでもいい" },
{ en: "Perfect.", jp: "完璧" },
{ en: "Sure.", jp: "いいよ" },
{ en: "Let me think.", jp: "ちょっと考える" },
{ en: "How should I say this…", jp: "なんて言えばいいかな" },
{ en: "I mean…", jp: "つまり" },
{ en: "What I mean is…", jp: "言いたいのは" },
{ en: "To be honest…", jp: "正直言うと" },
{ en: "Actually…", jp: "実は" },
{ en: "By the way…", jp: "ところで" },
{ en: "Anyway…", jp: "とにかく" },
{ en: "Let’s see…", jp: "見てみよう" },
{ en: "You know…", jp: "あのね" },
{ en: "Well…", jp: "えっと" },
{ en: "So…", jp: "それで" },
{ en: "Like…", jp: "なんか" },
{ en: "I was like…", jp: "って思った" },
{ en: "You know what I mean?", jp: "分かる？" },
{ en: "What I’m saying is…", jp: "言いたいのは" },
{ en: "Basically…", jp: "要するに" },
{ en: "In other words…", jp: "言い換えると" },
{ en: "For example…", jp: "例えば" },
{ en: "I guess…", jp: "たぶん" },
{ en: "Give me a second.", jp: "ちょっと待って" },
{ en: "Hold on.", jp: "待って" },
{ en: "Let me check.", jp: "確認するね" },
{ en: "I’ll get back to you.", jp: "後で返事する" },
{ en: "I forgot.", jp: "忘れた" },
{ en: "I’m not ready yet.", jp: "まだ準備できてない" },
{ en: "Can you repeat that?", jp: "もう一回言って" },
{ en: "Speak slower, please.", jp: "ゆっくり話して" },
{ en: "I mean…", jp: "つまり" },
{ en: "What I meant was…", jp: "言いたかったのは" },
{ en: "That’s not what I meant.", jp: "そういう意味じゃない" },
{ en: "Let me rephrase.", jp: "言い直すね" },
{ en: "That came out wrong.", jp: "言い方ミスった" },
{ en: "I’m on my way.", jp: "今向かってる" },
{ en: "I’ll be there soon.", jp: "すぐ着く" },
{ en: "Running late.", jp: "遅れてる" },
{ en: "I’ll be there in 10 minutes.", jp: "10分で着く" },
{ en: "Let’s do it later.", jp: "後でやろう" },
{ en: "Not now.", jp: "今じゃない" },
{ en: "What’s up?", jp: "元気？" },
{ en: "Not much.", jp: "別に" },
{ en: "Same here.", jp: "こっちも" },
{ en: "I feel you.", jp: "分かるわ" },
{ en: "That sucks.", jp: "それ最悪だね" },
{ en: "Lucky you.", jp: "いいなあ" },
{ en: "I love it.", jp: "めっちゃ好き" },
{ en: "I hate it.", jp: "最悪" },
{ en: "I’m excited.", jp: "楽しみ" },
{ en: "I’m nervous.", jp: "緊張する" },
{ en: "I’m bored.", jp: "退屈" },
];
